TE5-T422 GridWithRecyclerActivity,ExpandableListView and ExpandableRe…
vishal2001prajapati/myrepo3 pull request #12
Opened 2022-03-25 09:57 UTC by vishal2001prajapati

…cyclerViewAdapter Complete.

2022-03-29 04:42 UTC, Purvesh-Dodiya requested changes

2022-03-29 04:42 UTC, Purvesh-Dodiya commented on app/src/main/java/com/example/myapplication3/Intent/FirstIntentActivity.kt
> +    private val channelId = "i.app.noffification"
move to constant file

2022-03-29 04:42 UTC, Purvesh-Dodiya commented on app/src/main/java/com/example/myapplication3/Intent/FirstIntentActivity.kt
> +                    .setContentTitle("Example Title")
remove static string

2022-03-29 09:01 UTC, purvesh-d requested changes

2022-03-29 09:01 UTC, purvesh-d commented on app/src/main/java/com/example/myapplication3/Intent/FirstIntentActivity.kt
> +    private val channelId = "i.app.noffification"
move to constatnt

2022-03-29 09:01 UTC, purvesh-d commented on app/src/main/java/com/example/myapplication3/Intent/FirstIntentActivity.kt
> +    private val notificationId = 101
same

2022-03-29 09:01 UTC, purvesh-d commented on app/src/main/java/com/example/myapplication3/Intent/FirstIntentActivity.kt
> +    private val notificationId = 101
pending

2022-03-29 09:01 UTC, purvesh-d commented on app/src/main/java/com/example/myapplication3/Intent/FirstIntentActivity.kt
> +            intent.putExtra("Data", data)
move key to constant

2022-03-29 09:01 UTC, purvesh-d commented on app/src/main/java/com/example/myapplication3/Intent/FirstIntentActivity.kt
> +            val intent = Intent(Intent.ACTION_VIEW, Uri.parse("https://www.youtube.com/"))
static string

2022-03-29 09:01 UTC, purvesh-d commented on app/src/main/java/com/example/myapplication3/Intent/SecondIntentActivity.kt
> +        val userData = intent.getStringExtra("Data")
static key

2022-03-30 04:55 UTC, purvesh-d approved these changes

2022-03-30 04:55 UTC, merged