TE5-T422 Recyclerview Added
vishal2001prajapati/myrepo3 pull request #8
Opened 2022-03-02 06:20 UTC by vishal2001prajapati

2022-03-02 09:22 UTC, Purvesh-Dodiya requested changes

2022-03-02 09:22 UTC, Purvesh-Dodiya commented on app/src/main/java/com/example/myapplication3/RecyclerView/ItemAdapter.kt
> +        holder.itemtext.text = itemList[position].str_text
you can put this line in below apply block

2022-03-02 09:22 UTC, Purvesh-Dodiya commented on app/src/main/java/com/example/myapplication3/RecyclerView/RecyclerViewActivity.kt
> +            title = "RecyclerView"
static string

2022-03-02 09:22 UTC, Purvesh-Dodiya commented on app/src/main/java/com/example/myapplication3/RecyclerView/RecyclerViewActivity.kt
> +        recycler_view.layoutManager = LinearLayoutManager(this)
use apply

2022-03-02 09:49 UTC, vishal2001prajapati commented on app/src/main/java/com/example/myapplication3/RecyclerView/ItemAdapter.kt
> +        holder.itemtext.text = itemList[position].str_text
in the holder holder itemtext and new itemcheck is diffrent statement so i give the apply is not work

2022-03-04 03:58 UTC, Purvesh-Dodiya requested changes

2022-03-04 03:58 UTC, Purvesh-Dodiya commented on app/src/main/java/com/example/myapplication3/RecyclerView/ItemAdapter.kt
> +        holder.itemtext.text = itemList[position].str_text
Pending

2022-03-04 04:15 UTC, merged